name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Mono
      run: |
         apt install gnupg ca-certificates
         apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
         echo "deb https://download.mono-project.com/repo/ubuntu stable-bionic main" | tee /etc/apt/sources.list.d/mono-official-stable.list
         apt update && apt install mono-complete
    - name: Build KitZ
      run: msbuild KitZ.sln
    - uses: actions/upload-artifact@master
      with:
        name: KitZ
        path: KitZ/bin/Release/KitZ.dll
